# Generated by Django 4.2.7 on 2023-11-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('music_file', models.FileField(upload_to='music/')),
                ('music_type', models.CharField(choices=[('effect', '효과음'), ('background', '배경음악')], max_length=100)),
                ('genre', models.CharField(choices=[('hiphop', '힙합'), ('rock', '락'), ('pop', '팝'), ('jazz', '재즈'), ('classic', '클래식'), ('blues', '블루스'), ('fork', '포크'), ('indie', '인디'), ('rnb', 'R&B')], max_length=100)),
                ('instruments', models.CharField(choices=[('piano', '피아노'), ('acoustic guitar', '어쿠스틱 기타'), ('bass', '베이스'), ('drum', '드럼'), ('violin', '바이올린')], max_length=100)),
                ('mood', models.CharField(choices=[('depressed', '우울한'), ('excited', '신나는'), ('happy', '쾌활한'), ('peaceful', '평화로운'), ('serious', '심각한'), ('urgent', '급박한'), ('horrifying', '소름 끼치는')], max_length=100)),
                ('length', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
