# Generated by Django 4.2.7 on 2023-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_downloads_music_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
