# Generated by Django 4.2.7 on 2023-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
