# Generated by Django 4.2.7 on 2023-11-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
