# Generated by Django 4.2.7 on 2023-11-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_music_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
