# Generated by Django 4.2.7 on 2023-11-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_alter_music_length"),
        ("music", "0008_alter_music_liker"),
    ]

    operations = []
