# Generated by Django 4.2.7 on 2023-11-09 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0009_merge_0006_music_music_image_0008_alter_music_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='liker',
            field=models.ManyToManyField(blank=True, default=[], related_name='like_music', to=settings.AUTH_USER_MODEL),
        ),
    ]
