# Generated by Django 4.2.7 on 2023-11-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_music_music_image"),
        ("music", "0009_merge_0005_alter_music_length_0008_alter_music_liker"),
    ]

    operations = []
