# Generated by Django 4.2.7 on 2023-11-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_music_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
