# Generated by Django 4.2.7 on 2023-11-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_merge_20231109_1353'),
        ('music', '0012_alter_music_length_alter_music_music_image'),
    ]

    operations = [
    ]
