# Generated by Django 4.2.7 on 2023-11-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_music_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='dblength',
            field=models.CharField(default='0:00:00', max_length=10),
        ),
    ]
